// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.9.0"
	GitCommit   = "e22b1d5"          // the commit JUST BEFORE the release
	VersionDate = "2023-01-09 08:37" // UTC
)
