// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v1.0.5"
	GitCommit   = "d2b80c7"          // the commit JUST BEFORE the release
	VersionDate = "2023-01-17 11:53" // UTC
)
