// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v1.0.1"
	GitCommit   = "34f34ae"          // the commit JUST BEFORE the release
	VersionDate = "2023-01-15 12:25" // UTC
)
