Name = "gosl"
ID = "com.emer.gosl.v2"
Version = "v2.0.0-dev0.0.8"
Type = "Library"

[Release]
  VersionFile = "version.go"
  Package = "main"

[Generate]
  [Generate.Enumgen]
    LineComment = false
    AcceptLower = true
  [Generate.Gtigen]
    AddTypes = false

